// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schaaktoernooi;

namespace Schaaktoernooi.Migrations
{
    [DbContext(typeof(SchaakContext))]
    [Migration("20190325210309_Classen maken")]
    partial class Classenmaken
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Schaaktoernooi.Club", b =>
                {
                    b.Property<int>("ClubID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ClubID");

                    b.ToTable("Club");
                });

            modelBuilder.Entity("Schaaktoernooi.MenuItem", b =>
                {
                    b.Property<int>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Nummer");

                    b.Property<string>("Omschrijving");

                    b.HasKey("MenuID");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("Schaaktoernooi.Toernooi", b =>
                {
                    b.Property<int>("TournamentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClubID");

                    b.Property<string>("TournamentDetails");

                    b.Property<DateTime>("TournamentEndDate");

                    b.Property<string>("TournamentName");

                    b.Property<DateTime>("TournamentStartDate");

                    b.HasKey("TournamentID");

                    b.HasIndex("ClubID");

                    b.ToTable("Toernooi");
                });

            modelBuilder.Entity("Schaaktoernooi.TournamentsForEachClub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClubID");

                    b.Property<int>("TournamentID");

                    b.HasKey("Id");

                    b.HasIndex("ClubID");

                    b.HasIndex("TournamentID");

                    b.ToTable("TournamentsForEachClubs");
                });

            modelBuilder.Entity("Schaaktoernooi.Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login");

                    b.Property<string>("Paswoord");

                    b.Property<bool>("Type");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Schaaktoernooi.Toernooi", b =>
                {
                    b.HasOne("Schaaktoernooi.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Schaaktoernooi.TournamentsForEachClub", b =>
                {
                    b.HasOne("Schaaktoernooi.Club", "Club")
                        .WithMany("tournamentsForEachClubs")
                        .HasForeignKey("ClubID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Schaaktoernooi.Toernooi", "Toernooi")
                        .WithMany("tournamentsForEachClubs")
                        .HasForeignKey("TournamentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
